import { gql } from '@apollo/client';
export const FETCH_POSTS_QUERY = gql`
    {
        getPosts{
            id
            body
            createdAt
            username
            user{
                username
            }
            likeCount
            likes{
                id
                createdAt
                user{
                    username
                }
            }
            commentCount
            comments{
                id
                body
                createdAt
                user{
                    username
                }
            }
        }
    }
`
